import { db } from '../packages/db/src/client.js';
import { sinks } from '../packages/db/src/schema/sinks.js';
import { companies } from '../packages/db/src/schema/companies.js';
import { eq } from 'drizzle-orm';

// Color definitions
const QUARTZ_COLORS = [
  { code: 'GR', name: 'Grey', hex: '#808080' },
  { code: 'BL', name: 'Black', hex: '#1a1a1a' },
  { code: 'WH', name: 'White', hex: '#f5f5f5' },
  { code: 'BR', name: 'Brown', hex: '#654321' },
  { code: 'BI', name: 'Bisque', hex: '#ffe4c4' },
  { code: 'CN', name: 'Concrete', hex: '#999999' },
];

const STAINLESS_COLORS = [
  { code: 'SS', name: 'Stainless Steel', hex: '#c0c0c0' },
];

const MATRIX_COLORS = [
  { code: 'SS', name: 'Stainless Steel', hex: '#c0c0c0' },
  { code: 'GM', name: 'Gunmetal Grey', hex: '#4a4a4a' },
];

const FIRECLAY_COLORS = [
  { code: 'WH', name: 'White', hex: '#ffffff' },
  { code: 'MB', name: 'Matte Black', hex: '#2a2a2a' },
];

// Karran sink models
const KARRAN_SINKS = [
  // ========================================
  // QUARTZ FARMHOUSE (QA/QAR) - Full Apron
  // ========================================
  {
    sku: 'QA-740',
    name: 'Karran QA-740 Quartz Farmhouse Double Equal Bowl',
    description: 'Quartz composite farmhouse sink with double equal bowls and full-depth apron front',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_farmhouse' as const,
    manufacturer: 'Karran',
    modelNumber: 'QA-740',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '9.25',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QA-750',
    name: 'Karran QA-750 Quartz Farmhouse Large/Small Bowl',
    description: 'Quartz composite farmhouse sink with large and small bowls and full-depth apron front',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_farmhouse' as const,
    manufacturer: 'Karran',
    modelNumber: 'QA-750',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '9.25',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // QUARTZ FARMHOUSE (QAR) - Short Apron
  // ========================================
  {
    sku: 'QAR-740',
    name: 'Karran QAR-740 Quartz Farmhouse Double Equal Bowl (Reduced Apron)',
    description: 'Quartz composite farmhouse sink with double equal bowls and reduced 6.5" apron depth',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_farmhouse' as const,
    manufacturer: 'Karran',
    modelNumber: 'QAR-740',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '6.5',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QAR-750',
    name: 'Karran QAR-750 Quartz Farmhouse Large/Small Bowl (Reduced Apron)',
    description: 'Quartz composite farmhouse sink with large and small bowls and reduced 6.5" apron depth',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_farmhouse' as const,
    manufacturer: 'Karran',
    modelNumber: 'QAR-750',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '6.5',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // QUARTZ TOP MOUNT (QT)
  // ========================================
  {
    sku: 'QT-810',
    name: 'Karran QT-810 Quartz Top Mount Double Equal Bowl',
    description: 'Quartz composite top mount sink with double equal bowls and 5 faucet holes',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_top_mount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QT-810',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QT-811',
    name: 'Karran QT-811 Quartz Top Mount Large/Small Bowl',
    description: 'Quartz composite top mount sink with large and small bowls and 3 faucet holes',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_top_mount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QT-811',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QT-812',
    name: 'Karran QT-812 Quartz Top Mount Single Bowl',
    description: 'Quartz composite top mount sink with single bowl and 5 faucet holes',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_top_mount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QT-812',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QT-820',
    name: 'Karran QT-820 Quartz Top Mount Single Bowl (25")',
    description: 'Quartz composite top mount sink with single bowl and 3 faucet holes',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '25',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_top_mount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QT-820',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QT-825',
    name: 'Karran QT-825 Quartz Top Mount Bar Sink',
    description: 'Quartz composite top mount bar sink',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '15.75',
    depthInches: '19.625',
    heightInches: '7.875',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_top_mount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QT-825',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'bar' as const,
    mfgMinCabinetWidthInches: '18',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // QUARTZ UNDERMOUNT (QU)
  // ========================================
  {
    sku: 'QU-810',
    name: 'Karran QU-810 Quartz Undermount Double Equal Bowl',
    description: 'Quartz composite undermount sink with double equal bowls',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32',
    depthInches: '19',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_undermount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QU-810',
    installationType: 'undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QU-811',
    name: 'Karran QU-811 Quartz Undermount Large/Small Bowl',
    description: 'Quartz composite undermount sink with large and small bowls',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32',
    depthInches: '19',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_undermount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QU-811',
    installationType: 'undermount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QU-812',
    name: 'Karran QU-812 Quartz Undermount Single Bowl',
    description: 'Quartz composite undermount sink with single bowl',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32',
    depthInches: '19',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_undermount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QU-812',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QU-820',
    name: 'Karran QU-820 Quartz Undermount Single Bowl (24")',
    description: 'Quartz composite undermount sink with single bowl',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '24.375',
    depthInches: '18.25',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_undermount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QU-820',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QU-825',
    name: 'Karran QU-825 Quartz Undermount Bar Sink',
    description: 'Quartz composite undermount bar sink',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '15.75',
    depthInches: '17.75',
    heightInches: '7.875',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_undermount' as const,
    manufacturer: 'Karran',
    modelNumber: 'QU-825',
    installationType: 'undermount' as const,
    bowlConfiguration: 'bar' as const,
    mfgMinCabinetWidthInches: '18',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // QUARTZ WORKSTATION
  // ========================================
  {
    sku: 'QAWS-740',
    name: 'Karran QAWS-740 Quartz Farmhouse Workstation Single Bowl',
    description: 'Quartz composite farmhouse workstation sink with accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.125',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QAWS-740',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '9.125',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QARWS-740',
    name: 'Karran QARWS-740 Quartz Farmhouse Workstation Single Bowl (Reduced Apron)',
    description: 'Quartz composite farmhouse workstation sink with reduced apron and accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '34',
    depthInches: '21.25',
    heightInches: '9.125',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QARWS-740',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '6.5',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QUWS-875',
    name: 'Karran QUWS-875 Quartz Undermount Workstation Single Bowl',
    description: 'Quartz composite undermount workstation sink with accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32.375',
    depthInches: '19.5',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QUWS-875',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QTWS-875',
    name: 'Karran QTWS-875 Quartz Top Mount Workstation Single Bowl',
    description: 'Quartz composite top mount workstation sink with accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QTWS-875',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QUWS-880',
    name: 'Karran QUWS-880 Quartz Undermount Workstation Double Equal Bowl',
    description: 'Quartz composite undermount workstation sink with double equal bowls and accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32.5',
    depthInches: '19.25',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QUWS-880',
    installationType: 'undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },
  {
    sku: 'QTWS-880',
    name: 'Karran QTWS-880 Quartz Top Mount Workstation Double Equal Bowl',
    description: 'Quartz composite top mount workstation sink with double equal bowls and accessories',
    material: 'quartz_composite' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'QTWS-880',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // QUARTZ SEAMLESS
  // ========================================
  {
    sku: 'Q-360R',
    name: 'Karran Q-360R Quartz Seamless Undermount Large/Small Bowl',
    description: 'Quartz composite seamless undermount sink for solid surface/laminate countertops',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32.5',
    depthInches: '19.125',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_seamless' as const,
    manufacturer: 'Karran',
    modelNumber: 'Q-360R',
    installationType: 'seamless_undermount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
    countertopCompatibility: ['laminate', 'solid_surface'],
  },
  {
    sku: 'Q-350',
    name: 'Karran Q-350 Quartz Seamless Undermount Single Bowl',
    description: 'Quartz composite seamless undermount sink for solid surface/laminate countertops',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '30.875',
    depthInches: '18.875',
    heightInches: '9.25',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_seamless' as const,
    manufacturer: 'Karran',
    modelNumber: 'Q-350',
    installationType: 'seamless_undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
    countertopCompatibility: ['laminate', 'solid_surface'],
  },
  {
    sku: 'Q-340',
    name: 'Karran Q-340 Quartz Seamless Undermount Double Equal Bowl',
    description: 'Quartz composite seamless undermount sink',
    material: 'quartz_composite' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '32.5',
    depthInches: '19.125',
    heightInches: '9.25',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'quartz_seamless' as const,
    manufacturer: 'Karran',
    modelNumber: 'Q-340',
    installationType: 'seamless_undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    heatSafeTempF: 535,
    templateIncluded: true,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: QUARTZ_COLORS,
  },

  // ========================================
  // ELITE STAINLESS UNDERMOUNT
  // ========================================
  {
    sku: 'EL-78R',
    name: 'Karran EL-78R Elite Stainless Undermount Large/Small Bowl (Right)',
    description: '16-gauge stainless steel undermount sink with large bowl on right',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '31.5',
    depthInches: '18.5',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-78R',
    installationType: 'undermount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'rear' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-78L',
    name: 'Karran EL-78L Elite Stainless Undermount Large/Small Bowl (Left)',
    description: '16-gauge stainless steel undermount sink with large bowl on left',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '31.5',
    depthInches: '18.5',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-78L',
    installationType: 'undermount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'rear' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-77',
    name: 'Karran EL-77 Elite Stainless Undermount Double Equal Bowl',
    description: '16-gauge stainless steel undermount sink with double equal bowls',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '31.5',
    depthInches: '18.5',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-77',
    installationType: 'undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-79',
    name: 'Karran EL-79 Elite Stainless Undermount Single Bowl (30")',
    description: '16-gauge stainless steel undermount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '30',
    depthInches: '18.25',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-79',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-76',
    name: 'Karran EL-76 Elite Stainless Undermount Single Bowl (23.5")',
    description: '16-gauge stainless steel undermount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '23.5',
    depthInches: '17.75',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-76',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-75',
    name: 'Karran EL-75 Elite Stainless Undermount Single Bowl (8" deep)',
    description: '18-gauge stainless steel undermount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '23.5',
    depthInches: '17.75',
    heightInches: '8',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-75',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-74',
    name: 'Karran EL-74 Elite Stainless Undermount Bar Sink',
    description: '16-gauge stainless steel undermount bar sink',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '15.75',
    depthInches: '18.5',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-74',
    installationType: 'undermount' as const,
    bowlConfiguration: 'bar' as const,
    mfgMinCabinetWidthInches: '18',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-73',
    name: 'Karran EL-73 Elite Stainless Undermount Single Bowl (23.25")',
    description: '18-gauge stainless steel undermount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '23.25',
    depthInches: '17.75',
    heightInches: '8',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-73',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-71',
    name: 'Karran EL-71 Elite Stainless Undermount Bar Sink (14.75")',
    description: '18-gauge stainless steel undermount bar sink',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '14.75',
    depthInches: '17.75',
    heightInches: '8',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-71',
    installationType: 'undermount' as const,
    bowlConfiguration: 'bar' as const,
    mfgMinCabinetWidthInches: '18',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },

  // ========================================
  // ELITE STAINLESS TOP MOUNT
  // ========================================
  {
    sku: 'EL-35',
    name: 'Karran EL-35 Elite Stainless Top Mount Double Equal Bowl',
    description: '18-gauge stainless steel top mount sink with double equal bowls',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-35',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 4,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-33',
    name: 'Karran EL-33 Elite Stainless Top Mount Single Bowl',
    description: '18-gauge stainless steel top mount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-33',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 4,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'EL-30',
    name: 'Karran EL-30 Elite Stainless Top Mount Single Bowl (25")',
    description: '18-gauge stainless steel top mount sink with single bowl',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '25',
    depthInches: '22',
    heightInches: '9',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_stainless' as const,
    manufacturer: 'Karran',
    modelNumber: 'EL-30',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '18G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: STAINLESS_COLORS,
  },

  // ========================================
  // ELITE WORKSTATION - FARMHOUSE APRON
  // ========================================
  {
    sku: 'WSA-48',
    name: 'Karran WSA-48 Elite Workstation Farmhouse Single Bowl (36")',
    description: '16-gauge stainless steel farmhouse workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '36',
    depthInches: '22.25',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSA-48',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '10',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WSA-46',
    name: 'Karran WSA-46 Elite Workstation Farmhouse Single Bowl (33")',
    description: '16-gauge stainless steel farmhouse workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '33',
    depthInches: '22.25',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSA-46',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '10',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WSA-45',
    name: 'Karran WSA-45 Elite Workstation Farmhouse Large/Small Bowl',
    description: '16-gauge stainless steel farmhouse workstation sink with large and small bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '33',
    depthInches: '22.25',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSA-45',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '10',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WSA-42',
    name: 'Karran WSA-42 Elite Workstation Farmhouse Single Bowl (30")',
    description: '16-gauge stainless steel farmhouse workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '30',
    depthInches: '22.25',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSA-42',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '30',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    apronDepthInches: '10',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },

  // ========================================
  // ELITE WORKSTATION - TOP MOUNT
  // ========================================
  {
    sku: 'WST-28',
    name: 'Karran WST-28 Elite Workstation Top Mount Single Bowl',
    description: '16-gauge stainless steel top mount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WST-28',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WST-26',
    name: 'Karran WST-26 Elite Workstation Top Mount Large/Small Bowl',
    description: '16-gauge stainless steel top mount workstation sink with large and small bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WST-26',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WST-23',
    name: 'Karran WST-23 Elite Workstation Top Mount Double Equal Bowl',
    description: '16-gauge stainless steel top mount workstation sink with double equal bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '33',
    depthInches: '22',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WST-23',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 5,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WST-22',
    name: 'Karran WST-22 Elite Workstation Top Mount Single Bowl (25")',
    description: '16-gauge stainless steel top mount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '25',
    depthInches: '22',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WST-22',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Zero Radius',
    steelGauge: '16G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WST-20',
    name: 'Karran WST-20 Elite Workstation Top Mount Single Bowl Zero-Radius',
    description: '16-gauge stainless steel top mount workstation sink with zero-radius corners and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'drop_in' as const,
    widthInches: '25',
    depthInches: '22',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WST-20',
    installationType: 'top_mount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '27',
    faucetHoles: 3,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Zero Radius',
    steelGauge: '16G',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },

  // ========================================
  // ELITE WORKSTATION - UNDERMOUNT
  // ========================================
  {
    sku: 'WS-100',
    name: 'Karran WS-100 Elite Workstation Undermount Large/Small Bowl (45")',
    description: '16-gauge stainless steel undermount workstation sink with large and small bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '45',
    depthInches: '19',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WS-100',
    installationType: 'undermount' as const,
    bowlConfiguration: 'large_small' as const,
    mfgMinCabinetWidthInches: '48',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },
  {
    sku: 'WS-90',
    name: 'Karran WS-90 Elite Workstation Undermount Single Bowl (45")',
    description: '16-gauge stainless steel undermount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '45',
    depthInches: '19',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'elite_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WS-90',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '48',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: STAINLESS_COLORS,
  },

  // ========================================
  // MATRIX WORKSTATION
  // ========================================
  {
    sku: 'WSTMSB3833',
    name: 'Karran WSTMSB3833 Matrix Workstation Undermount Single Bowl (38.5")',
    description: '16-gauge stainless steel/gunmetal grey undermount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '38.5',
    depthInches: '19.5',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'matrix_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSTMSB3833',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '42',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: MATRIX_COLORS,
  },
  {
    sku: 'WSTMSB3633',
    name: 'Karran WSTMSB3633 Matrix Workstation Undermount Single Bowl (36.5")',
    description: '16-gauge stainless steel/gunmetal grey undermount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '36.5',
    depthInches: '19.5',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'matrix_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSTMSB3633',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '39',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: MATRIX_COLORS,
  },
  {
    sku: 'WSTMSB2833',
    name: 'Karran WSTMSB2833 Matrix Workstation Undermount Single Bowl (28.5")',
    description: '16-gauge stainless steel/gunmetal grey undermount workstation sink with accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '28.5',
    depthInches: '19.5',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'matrix_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSTMSB2833',
    installationType: 'undermount' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '30',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: MATRIX_COLORS,
  },
  {
    sku: 'WSTMDB3633',
    name: 'Karran WSTMDB3633 Matrix Workstation Undermount Double Equal Bowl (36.5")',
    description: '16-gauge stainless steel/gunmetal grey undermount workstation sink with double equal bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '36.5',
    depthInches: '19.5',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'matrix_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSTMDB3633',
    installationType: 'undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '39',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: MATRIX_COLORS,
  },
  {
    sku: 'WSTMDB2833',
    name: 'Karran WSTMDB2833 Matrix Workstation Undermount Double Equal Bowl (28.5")',
    description: '16-gauge stainless steel/gunmetal grey undermount workstation sink with double equal bowls and accessories',
    material: 'stainless_steel' as const,
    mountingStyle: 'undermount' as const,
    widthInches: '28.5',
    depthInches: '19.5',
    heightInches: '10',
    bowlCount: 2,
    basePrice: '0',
    laborCost: '0',
    series: 'matrix_workstation' as const,
    manufacturer: 'Karran',
    modelNumber: 'WSTMDB2833',
    installationType: 'undermount' as const,
    bowlConfiguration: 'double_equal' as const,
    mfgMinCabinetWidthInches: '30',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Tight Radius',
    steelGauge: '16G',
    templateIncluded: true,
    clipsIncluded: true,
    isWorkstation: true,
    accessoriesIncluded: ['colander', 'cutting board', 'drying rack'],
    availableColors: MATRIX_COLORS,
  },

  // ========================================
  // FIRECLAY FARMHOUSE
  // ========================================
  {
    sku: 'FCP30SB',
    name: 'Karran FCP30SB Fireclay Farmhouse Single Bowl (30")',
    description: 'Fireclay farmhouse sink with reversible apron front',
    material: 'fireclay' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '30',
    depthInches: '18',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'fireclay' as const,
    manufacturer: 'Karran',
    modelNumber: 'FCP30SB',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '33',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Standard',
    apronDepthInches: '10',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: FIRECLAY_COLORS,
  },
  {
    sku: 'FCP33SB',
    name: 'Karran FCP33SB Fireclay Farmhouse Single Bowl (33")',
    description: 'Fireclay farmhouse sink with reversible apron front',
    material: 'fireclay' as const,
    mountingStyle: 'farmhouse' as const,
    widthInches: '33',
    depthInches: '18',
    heightInches: '10',
    bowlCount: 1,
    basePrice: '0',
    laborCost: '0',
    series: 'fireclay' as const,
    manufacturer: 'Karran',
    modelNumber: 'FCP33SB',
    installationType: 'farmhouse_apron' as const,
    bowlConfiguration: 'single' as const,
    mfgMinCabinetWidthInches: '36',
    faucetHoles: 0,
    drainSize: '3 5/8"',
    drainLocation: 'center' as const,
    cornerRadius: 'Standard',
    apronDepthInches: '10',
    templateIncluded: false,
    clipsIncluded: false,
    isWorkstation: false,
    availableColors: FIRECLAY_COLORS,
  },
];

async function main() {
  console.log('🚀 Karran Sink Catalogue Seeding Script\n');

  // Get company ID from command line or find first company
  const companyIdArg = process.argv[2];

  let targetCompanyId: string;

  if (companyIdArg) {
    targetCompanyId = companyIdArg;
    console.log(`Using provided company ID: ${targetCompanyId}\n`);
  } else {
    console.log('No company ID provided. Looking up first company in database...');
    const [company] = await db.select().from(companies).limit(1);

    if (!company) {
      console.error('❌ No company found in database. Please pass a companyId as argument.');
      console.error('   Usage: tsx scripts/seed-karran-catalogue.ts <companyId>');
      process.exit(1);
    }

    targetCompanyId = company.id;
    console.log(`✅ Using company: ${company.name} (${company.id})\n`);
  }

  let inserted = 0;
  let skipped = 0;

  console.log(`Processing ${KARRAN_SINKS.length} sink models...\n`);

  for (const sink of KARRAN_SINKS) {
    // Check if SKU already exists
    const existing = await db.query.sinks.findFirst({
      where: eq(sinks.sku, sink.sku),
    });

    if (existing) {
      console.log(`  ⏭️  SKIP: ${sink.sku} (already exists)`);
      skipped++;
      continue;
    }

    // Insert new sink
    await db.insert(sinks).values({
      companyId: targetCompanyId,
      ...sink,
    });

    console.log(`  ✅ INSERT: ${sink.sku} - ${sink.name}`);
    inserted++;
  }

  console.log('\n' + '='.repeat(70));
  console.log(`✨ Seeding Complete!`);
  console.log(`   Inserted: ${inserted} sinks`);
  console.log(`   Skipped:  ${skipped} sinks (already existed)`);
  console.log(`   Total:    ${KARRAN_SINKS.length} models processed`);
  console.log('='.repeat(70) + '\n');

  process.exit(0);
}

main().catch((error) => {
  console.error('❌ Error seeding Karran catalogue:', error);
  process.exit(1);
});
